package com.dicoding.picodiploma.hewan

object DataHewan {
    private var data = arrayOf(
        arrayOf(
            "Ayam",
            R.drawable.ayam,
            "Ayam adalah hewan aves atau unggas yang bernafas dengan paru-paru, memiliki paruh dan memiliki 2 kaki yang fungsinya untuk menggaruk tanah agar bisa mencari makan. Ayam merupakan jenis burung yang akan dimanfaatkan daging, telur, dan bulunya. Pada umunya hewan ini termasuk bagian dari rasa atau ordo gallifermos dan anserifornes, biasanya hewan ini sering dijadikan hewan ternak atau hewan peliharaan." +
                    "\n\nDengan populasi lebih dari 24 miliar pada tahun 2003, Firefly's Bird Encyclopaedia menyatakan ada lebih banyak ayam di dunia ini daripada burung lainnya. Ayam memasok dua sumber protein dalam pangan: daging ayam dan telur.\n" +
                    "\n\nSudut pandang tradisional peternakan ayam dalam domestikasi spesies ini termaktub dalam Encyclopædia Britannica (2007): \"Manusia pertama mendomestikasi ayam asal India untuk keperluan adu ayam di Asia, Afrika, dan Eropa. Tidak ada perhatian khusus diberikan ke produksi telur atau daging." +
                    "\n\nAyam peliharaan berasal dari domestikasi ayam hutan merah (ayam bangkiwa, Gallus gallus) yang hidup di India. Namun demikian, pengujian molekular menunjukkan kemungkinan sumbangan plasma nutfah dari G. sonneratii, karena ayam hutan merah tidak memiliki sifat kulit warna kuning yang menjadi salah satu ciri ayam peliharaan." +
                    "\n\nAyam menunjukkan perbedaan morfologi di antara kedua tipe kelamin (dimorfisme seksual). Ayam jantan (jago, rooster) lebih atraktif, berukuran lebih besar, memiliki jalu panjang, berjengger lebih besar, dan bulu ekornya panjang menjuntai. Ayam betina (babon, hen) relatif kecil, berukuran kecil, jalu pendek atau nyaris tidak kelihatan, berjengger kecil, dan bulu ekor pendek. Perkelaminan ini diatur oleh sistem hormon. Apabila terjadi gangguan pada fungsi fisiologi tubuhnya, ayam betina dapat berganti kelamin menjadi jantan karena ayam dewasa masih memiliki ovotestis yang dorman dan sewaktu-waktu dapat aktif." +
                    "Ayam jantan yang sedang berkokok di pagi hari." +
                    "\n\nSebagai hewan peliharaan, ayam mampu mengikuti ke mana manusia membawanya. Hewan ini sangat adaptif dan dapat dikatakan bisa hidup di sembarang tempat, asalkan tersedia makanan baginya. Karena kebanyakan ayam peliharaan sudah kehilangan kemampuan terbang yang baik, mereka lebih banyak menghabiskan waktu di tanah atau kadang-kadang di pohon." +
                    "\n\nAyam berukuran kecil kadang-kadang dimangsa oleh unggas pemangsa, seperti elang."
        ),
        arrayOf(
            "Gajah",
            R.drawable.gajah,
            "Gajah adalah mamalia besar dari famili Elephantidae dan ordo Proboscidea. Secara tradisional, terdapat dua spesies yang diakui, yaitu gajah afrika (Loxodonta africana) dan gajah asia (Elephas maximus), walaupun beberapa bukti menunjukkan bahwa gajah semak afrika dan gajah hutan afrika merupakan spesies yang berbeda (L. africana dan L. cyclotis). Gajah tersebar di seluruh Afrika sub-Sahara, Asia Selatan, dan Asia Tenggara. Elephantidae adalah satu-satunya famili dari ordo Proboscidea yang masih ada; famili lain yang kini sudah punah termasuk mamut dan mastodon. Gajah afrika jantan merupakan hewan darat terbesar dengan tinggi hingga 4 m dan massa yang juga dapat mencapai 7.000 kg. Gajah memiliki ciri-ciri khusus, dan yang paling mencolok adalah belalai atau proboscis yang digunakan untuk banyak hal, terutama untuk bernapas, menghisap air, dan mengambil benda. Gigi serinya tumbuh menjadi taring yang dapat digunakan sebagai senjata dan alat untuk memindahkan benda atau menggali. Daun telinganya yang besar membantu mengatur suhu tubuh mereka. Gajah afrika memiliki telinga yang lebih besar dan punggung yang cekung, sementara telinga gajah asia lebih kecil dan punggungnya cembung." +
                    "\n\nGajah merupakan hewan herbivora yang dapat ditemui di berbagai habitat, seperti sabana, hutan, gurun, dan rawa-rawa. Mereka cenderung berada di dekat air. Gajah dianggap sebagai spesies kunci karena dampaknya terhadap lingkungan. Hewan-hewan lain cenderung menjaga jarak dari gajah, dan predator-predator seperti singa, harimau. hyena, dan anjing liar biasanya hanya menyerang gajah muda. Gajah betina cenderung hidup dalam kelompok keluarga, yang terdiri dari satu betina dengan anak-anaknya atau beberapa betina yang berkerabat beserta anak-anak mereka. Kelompok ini dipimpin oleh individu gajah yang disebut matriark, yang biasanya merupakan betina tertua. Gajah memiliki struktur kelompok fisi-fusi, yaitu ketika kelompok-kelompok keluarga bertemu untuk bersosialisasi. Gajah jantan meninggalkan kelompok keluarganya ketika telah mencapai masa pubertas, dan akan tinggal sendiri atau bersama jantan lainnya. Jantan dewasa biasanya berinteraksi dengan kelompok keluarga ketika sedang mencari pasangan dan memasuki tahap peningkatan testosteron dan agresi yang disebut musth, yang membantu mereka mencapai dominasi dan keberhasilan reproduktif. Anak gajah merupakan pusat perhatian kelompok keluarga dan bergantung pada induknya selama kurang lebih tiga tahun. Gajah dapat hidup selama 70 tahun di alam bebas. Mereka berkomunikasi melalui sentuhan, penglihatan, penciuman, dan suara; gajah juga menggunakan infrasonik dan komunikasi seismik untuk jarak jauh. Kecerdasan gajah telah dibandingkan dengan kecerdasan primata dan cetacea. Mereka tampaknya memiliki kesadaran diri dan menunjukkan empati kepada gajah lain yang hampir atau sudah mati." +
                    "\n\nGajah afrika digolongkan sebagai spesies yang rentan oleh International Union for Conservation of Nature (IUCN), sementara gajah asia diklasifikasikan sebagai spesies terancam. Salah satu ancaman terbesar bagi gajah adalah perdagangan gading yang memicu perburuan liar. Ancaman lain adalah kehancuran habitat dan konflik dengan penduduk setempat. Di sisi lain, gajah digunakan sebagai hewan pekerja di Asia. Dulu mereka pernah digunakan untuk perang; kini, gajah sering kali dipertontonkan di kebun binatang dan sirkus. Gajah dapat dengan mudah dikenali dan telah digambarkan dalam seni, cerita rakyat, agama, sastra, dan budaya populer."
        ),
        arrayOf(
            "Harimau",
            R.drawable.harimau,
            "Harimau adalah hewan yang tergolong dalam filum Chordata, subfilum vertebrata, kelas mamalia, pemakan daging, keluarga felidae, genus panthera, dan tergolong dalam spesies tigris. Harimau adalah jenis kucing terbesar dari spesiesnya, bahkan lebih besar dari singa" +
                    "\n\nHarimau adalah jenis kucing terbesar dari spesiesnya, bahkan lebih besar dari singa. Harimau juga adalah kucing tercepat kedua dalam berlari, setelah citah. Dalam keseluruhan karnivora, harimau adalah kucing karnivora terbesar dan karnivora terbesar ketiga setelah beruang kutub dan beruang coklat." +
                    "\n\nHarimau biasanya memburu mangsa yang agak besar seperti rusa sambar, kijang, babi, atau kancil. Namun, harimau akan memburu hewan kecil seperti landak apabila mangsa yang agak besar itu tidak ada. Meskipun berasal dari keluarga yang sama, harimau berbeda dengan kucing biasa yang kecil, harimau sangat suka berenang, dan pada dasarnya kucing takut dengan air." +
                    "\n\nHarimau dikenal sebagai kucing terbesar, harimau berukuran seperti singa tetapi sedikit lebih berat. Beda subspesies harimau memiliki karakteristik yang berbeda juga, pada umumnya harimau jantan memiliki berat antara 180 dan 320 kg dan betina berbobot antara 120 dan 180 kg. Panjang jantan antara 2,6 dan 3,3 meter, sedangkan betina antara 2,3 dan 2,75 meter. Di antara subspesies yang masih hidup, harimau sumatra adalah yang paling kecil dan harimau siberia yang paling besar." +
                    "\n\nLoreng pada kebanyakan harimau bervariasi dari coklat ke hitam. Bentuk dan kepadatan lorengnya berbeda-beda subspesies satu dengan yang lain, tetapi hampir semua harimau memiliki lebih dari 100 loreng. Harimau jawa yang sekarang sudah punah kemungkinan memiliki loreng yang lebih banyak lagi. Pola loreng unik setiap harimau, dan dapat digunakan untuk membedakan satu sama lain, mirip dengan fungsi sidik jari yang digunakan untuk mengindentifikasi orang. Ini bukan, bagaimanapun juga, metode pengidentifikasian yang disarankan, terkait kesulitan untuk merekam pola loreng pada harimau liar. Sepertinya fungsi loreng adalah untuk kamuflase, untuk menyembunyikan mereka dari mangsanya."
        ),
        arrayOf(
            "Itik",
            R.drawable.itik,
            "Bebek atau itik adalah nama umum untuk beberapa spesies burung dalam famili Anatidae. Bebek umumnya adalah burung akuatik yang sebagian besar berukuran lebih kecil dibandingkan kerabatnya, angsa dan angsa berleher pendek, dan dapat ditemukan pada perairan air tawar maupun air laut." +
                    "\n\nBebek kadang-kadang disamakan dengan beberapa burung air yang berhubungan jauh namun mirip dalam penampilan, misalnya loon, grebe, gallinule, dan coot." +
                    "\n\nBeberapa jenis bebek juga dapat melakukan kawin silang, tetapi menghasilkan keturunan yang steril dan tidak bisa memiliki keturunan. Seperti persilangan antara serati dan bebek pelari dapat menghasilkan keturunan yang steril, brati dan tiktok." +
                    "\n\nSecara keseluruhan tubuh bebek berlekuk dan lebar, dan memiliki leher yang relatif panjang, meski tidak sepanjang angsa dan angsa berleher pendek. Bentuk tubuh bebek bervariasi dan umumnya membulat. Paruhnya berbentuk lebar dan mengandung lamellae yang berguna sebagai penyaring makanan. Pada spesies penangkap ikan, paruhnya berbentuk lebih panjang dan lebih kuat. Kakinya yang bersisik kuat dan terbentuk dengan baik, dan umumnya berada jauh di belakang tubuh, yang umum terdapat pada burung akuatik. Sayapnya sangat kuat dan umumnya pendek. Penerbangan bebek membutuhkan kepakan berkelanjutan sehingga membutuhkan otot sayap yang kuat. Tiga spesies bebek steamer tidak dapat terbang." +
                    "\n\nBebek jantan dari spesies di belahan bumi utara kadang-kadang memiliki warna bulu yang menarik. Spesies dari belahan bumi selatan tidak menunjukkan dimorfisme seksual kecuali Paradise Shelduck di Selandia Baru yang warna bebek betina lebih cerah daripada bebek jantan. Warna bebek muda, entah itu jantan atau betina, umumnya lebih mirip bebek betina dewasa." +
                    "\n\nBebek memakan makanan yang bervariasi, seperti rumput, tanaman air, ikan, serangga, amfibi kecil, cacing, dan moluska kecil. Bebek penyelam dan bebek laut mencari makanan di kedalaman air. Untuk memudahkan mereka dalam menyelam, kedua jenis bebek tersebut memiliki massa yang lebih besar sehingga mereka lebih sulit untuk terbang." +
                    "\n\nBebek dari subfamili Anatinae tidak mampu menyelam jauh. Mereka hanya menyaring makanan dari perairan yang mampu mereka jangkau. Jika mereka menyelam, mereka tidak dapat menyelam sejauh bebek penyelam. Untuk memudahkan penyaringan, mereka memiliki paruh pipih dan lebar serta mengandung lamellae."
        ),
        arrayOf(
            "Kanguru",
            R.drawable.kanguru,
            "Kanguru adalah hewan khas Australia. Ia termasuk dalam kelompok mamalia yang memiliki kantung atau disebut juga marsupialia. Kanguru adalah satu-satunya mamalia yang bisa melompat. Tinggi kanguru bisa mencapai 1-8 meter. Sedangkan beratnya 40-200 kg. Itu tadi beberapa fakta tentang kanguru." +
                    "\n\nTerdapat rumor bahwa arti kata kanggaroo adalah \"Saya tidak tahu\" dalam bahasa aborigin Australia. Alkisah, pada suatu hari, pelaut Amerika-Inggris mendarat di Australia dan melihat seekor hewan yang sangat unik, berkantung. Pelaut itu lalu bertanya kepada orang suku Aborigin, suku asli Australia di sana. Pelaut bertanya, \"hewan apakah itu?\" dan dijawab, \"Kang-Ga-Roo.\" Pelaut menganggap Kanggaroo adalah nama hewan itu, maka mereka menamainya Kanggaroo, padahal orang Aborigin itu berkata, \"Saya tidak mengerti!\"." +
                    "\n\nRumor ini tidak benar. Kata kanguru berasal dari bahasa aborigin Australia gangurru yang merupakan nama salah satu spesies hewan berkantung, disinyalir sebagai salah satu spesies kangguru."
        ),
        arrayOf(
            "Kelinci",
            R.drawable.kelinci,
            "Kelinci adalah hewan mamalia dari famili Leporidae, yang dapat ditemukan di banyak bagian bumi. Kelinci berkembangbiak dengan cara beranak yang disebut vivipar. Dulunya, hewan ini adalah hewan liar yang hidup di Afrika hingga ke daratan Eropa. Pada perkembangannya, tahun 1912, kelinci diklasifikasikan dalam ordo Lagomorpha. Ordo ini dibedakan menjadi dua famili, yakni Ochtonidae (jenis pika yang pandai bersiul) dan Leporidae (termasuk di dalamnya jenis kelinci dan terwelu). Asal kata kelinci berasal dari bahasa Belanda, yaitu konijntje yang berarti \"anak kelinci\". Hal ini menunjukkan bahwa masyarakat Nusantara mulai mengenali kelinci saat masa kolonial, padahal di Pulau Sumatra ada satu spesies asli kelinci sumatera (Nesolagus netscheri) yang baru ditemukan pada tahun 1972." +
                    "\n\nSaat ini sejumlah jenis kelinci menjadi hewan peliharaan dan hewan pedaging. Beberapa jenis kelinci sebagai hewan pedaging juga ada yang dijadikan hewan peliharaan. Jenis kelinci terbesar di dunia, yaitu Continental Giant biasanya dijadikan hewan pedaging, tetapi ada juga yang memeliharanya dan secara resmi telah menjadi kelinci terbesar di dunia dengan tinggi/panjang 4 feet + 4 inci (132 sentimeter) dan berat 3,5 stones (22,2 kilogram)." +
                    "\n\nSecara umum, kelinci terbagi menjadi dua jenis. Pertama, kelinci liar. Kedua, kelinci peliharaan. Yang termasuk dalam kategori kelinci liar adalah terwelu (Lepus curpaeums) dan kelinci liar (Oryctolagus cuniculus)." +
                    "\n\nDilihat dari jenis bulunya, kelinci ini terdiri dari jenis berbulu pendek dan panjang dengan warna yang agak kekuningan. Ketika musim dingin, warna kekuningan berubah menjadi kelabu." +
                    "\n\nMenurut rasnya, kelinci terbagi menjadi beberapa jenis, di antaranya Angora, Lyon, American Chinchilla, Dutch, English Spot, Himalayan, dan lain-lain. Khusus Lyon sebenarnya adalah hasil dari persilangan luar antara Angora dengan ras lainnya. Namun di kalangan peternak kelinci hias, hasil persilangan itu disebut sebagai Lyon atau Angora jadi-jadian." +
                    "\n\nDi Indonesia banyak terdapat kelinci lokal, yakni jenis kelinci jawa (Lepus negricollis) dan kelinci Sumatra (Nesolagus netseherischlgel). Kelinci jawa diperkirakan masih ada di hutan-hutan sekitar wilayah Jawa Barat. Warna bulunya cokelat perunggu kehitaman. Ekornya berwarna jingga dengan ujungnya yang hitam. Berat Kelinci jawa dewasa bisa mencapai 4 kg. Sedangkan Kelinci sumatera, merupakan satu-satunya ras kelinci yang asli Indonesia. Habitatnya adalah hutan di pegunungan Pulau Sumatra. Panjang badannya mencapai 40 cm. Warna bulunya kelabu cokelat kekuningan."
        ),
        arrayOf(
            "Kucing",
            R.drawable.kucing,
            "Kucing disebut juga kucing domestik atau kucing rumah adalah sejenis mamalia karnivora dari keluarga Felidae. Kata \"kucing\" biasanya merujuk kepada \"kucing\" yang telah dijinakkan, tetapi bisa juga merujuk kepada \"kucing besar\" seperti singa dan harimau" +
                    "\n\nKucing telah berbaur dengan kehidupan manusia paling tidak sejak 6.000 tahun SM, dari kerangka kucing di Pulau Siprus.[7] Orang Mesir Kuno dari 3.500 SM telah menggunakan kucing untuk menjauhkan tikus atau hewan pengerat lain dari lumbung yang menyimpan hasil panen." +
                    "\n\nSaat ini, kucing adalah salah satu hewan peliharaan terpopuler di dunia.[9] Kucing yang garis keturunannya tercatat secara resmi sebagai kucing trah atau galur murni (pure breed), seperti persia, siam, manx, dan sphinx. Kucing seperti ini biasanya dibiakkan di tempat pemeliharaan hewan resmi. Jumlah kucing ras hanyalah 1% dari seluruh kucing di dunia, sisanya adalah kucing dengan keturunan campuran seperti kucing liar atau kucing kampung." +
                    "\n\nFelidae adalah familia mamalia yang berevolusi dengan cepat yang berbagi nenek moyang yang sama hanya 10–15 juta tahun yang lalu[10] dan mencakup singa, harimau, cougar dan banyak lainnya. Dalam familia ini, kucing domestik (Felis catus) merupakan bagian dari genus Felis, yang merupakan kelompok kucing kecil yang berisi sekitar tujuh spesies (tergantung pada skema klasifikasi).[4][11] Anggota dari genus ini ditemukan di seluruh dunia dan termasuk kucing hutan (Felis chaus) dari tenggara Asia, kucing liar Eropa (F. silvestris silvestris), kucing liar Afrika (F. s. lybica), kucing gunung Cina (F. bieti), dan kucing pasir Arab (F. margarita), antara lain." +
                    "\n\nKucing domestik pertama kali diklasifikasikan sebagai Felis catus oleh Carolus Linnaeus dalam edisi ke-10 Systema Naturae-nya yang diterbitkan pada tahun 1758.[4][13] Karena filogenetika modern, kucing domestik biasanya dianggap sebagai subspesies dari kucing liar, F. silvestris.[4][1][14] Hal ini mengakibatkan penggunaan istilah yang bercampur, karena kucing domestik dapat disebut dengan nama subspesiesnya, Felis silvestris catus.[4][1][14] Kucing liar juga telah disebut sebagai berbagai subspesies F. catus,[14] tetapi pada tahun 2003, International Commission on Zoological Nomenclature menetapkan nama untuk kucing liar sebagai F. silvestris.[15] Nama yang paling umum digunakan untuk kucing domestik tetap F. catus, mengikuti konvensi untuk hewan peliharaan menggunakan sinonim pertama (senior) yang diusulkan.[15] Kadang-kadang, kucing domestik disebut sebagai Felis domesticus[16] atau Felis domestica,[4] seperti yang diusulkan oleh naturalis Jerman J. C. P. Erxleben pada tahun 1777 tetapi ini bukan nama-nama taksonomi valid dan jarang digunakan dalam literatur ilmiah,[16] karena binomial Linnaeus diutamakan.[17] Sebuah populasi kucing liar hitam Transkaukasia pernah diklasifikasikan sebagai Felis daemon (Satunin 1904) tetapi sekarang populasi ini dianggap menjadi bagian dari kucing domestik." +
                    "\n\nSemua kucing dalam genus ini berbagi nenek moyang yang sama yang mungkin hidup sekitar 6–7 juta tahun yang lalu di Asia.[19] Hubungan yang tepat dalam Felidae dekat tetapi masih belum pasti,[20][21] misalnya kucing gunung Cina kadang-kadang diklasifikasikan (dengan nama Felis silvestris bieti) sebagai upaspesies kucing liar, seperti varietas Afrika Utara F. s. lybica."
        ),
        arrayOf(
            "Kura-kura",
            R.drawable.kura,
            "Kura-kura adalah hewan bersisik berkaki empat yang termasuk golongan reptil. Bangsa hewan yang disebut Testudinata ini khas dan mudah dikenali dengan adanya ‘rumah’ atau batok yang keras dan kaku. Batok kura-kura ini terdiri dari dua bagian" +
                    "\n\nBatok kura-kura ini terdiri dari dua bagian. Bagian atas yang menutupi punggung disebut karapas (carapace) dan bagian bawah (ventral, perut) disebut plastron. Kemudian setiap bagiannya ini terdiri dari dua lapis. Lapis luar umumnya berupa sisik-sisik besar dan keras, dan tersusun seperti genting; sementara lapis bagian dalam berupa lempeng-lempeng tulang yang tersusun rapat seperti tempurung. Perkecualian terdapat pada kelompok labi-labi (Trionychoidea) dan jenis penyu belimbing, yang lapis luarnya tiada bersisik dan digantikan lapisan kulit di bagian luar tempurung tulangnya." +
                    "\n\nDalam bahasa Indonesia, kita mengenal tiga kelompok hewan yang termasuk bangsa ini, ialah penyu (bahasa Inggris: sea turtles), labi-labi atau bulus (freshwater turtles), dan kura-kura (tortoises). Dalam bahasa Inggris, dibedakan lagi antara kura-kura darat (land tortoises) dan kura-kura air tawar (freshwater tortoises atau terrapins)." +
                    "\n\nBagaimana batok kura-kura itu terbentuk dan berkembang dalam proses evolusinya, belum diperoleh keterangan yang jelas. Fosil kura-kura tertua kedua yang berasal dari Masa Trias (sekitar 210 juta tahun silam), Proganochelys, telah berbentuk mirip dengan kura-kura masa kini. Perbedaannya, tulang belulang di bagian punggung belum begitu melebar dan belum semuanya menyatu membentuk tempurung yang sempurna. Kura-kura purba hidup dan berkembang kurang lebih sejaman dengan dinosaurus. Archelon, misalnya, merupakan kura-kura raksasa yang diameter tubuhnya dapat mencapai lebih dari 4 m. Fosil kura-kura tertua yang ditemukan saat ini adalah Odontochelys yang berasal dari sekitar 2 tahun silam." +
                    "\n\nBanyak jenis kura-kura yang hidup sekarang mampu menyembunyikan kepala, kaki dan ekornya ke dalam tempurungnya, sehingga dapat menyelamatkan diri. Namun beberapa kura-kura primitif, seperti contohnya penyu, tak dapat menarik masuk anggota badannya itu."
        ),
        arrayOf(
            "Panda",
            R.drawable.panda,
            "Panda adalah salah satu hewan terunik di dunia. Mereka termasuk keluarga beruang, tapi warnanya lain sendiri dibanding semua beruang lain. Gak seperti beruang lain yang suka makan daging, panda malah lebih doyan makan pohon bambu. Mereka juga berbeda dengan beruang lain yang tampak garang, karena panda malah selalu tampak imut bahkan hingga dewasa." +
                    "\n\nPanda Raksasa (Ailuropoda melanoleuca, berarti \"Kaki-kucing hitam-putih\"; Hanzi sederhana: 大熊猫; Hanzi tradisional: 大熊貓; Pinyin: dà xióng māo; Jyutping: daai6 hung4 maau1, berarti \"kucing beruang besar\")[2] atau diringkas Panda, adalah seekor mamalia yang biasanya diklasifikasikan ke dalam keluarga beruang,[3] Ursidae, yang merupakan hewan asli Tiongkok Tengah. Panda Raksasa tinggal di wilayah pegunungan, seperti Sichuan dan Tibet. Pada setengah abad ke-20 terakhir, panda menjadi semacam lambang negara Tiongkok, dan sekarang ditampilkan pada uang emas negara tersebut." +
                    "\n\nMeskipun secara taksonomi ia adalah karnivora, makanannya seperti herbivora, sebagian besar tumbuh-tumbuhan, hampir hanya bambu saja. Secara teknis, seperti banyak hewan, panda adalah omnivora, karena diketahui mereka juga makan telur, dan juga serangga selain bambu. Kedua makanan ini adalah sumber protein yang diperlukan. Telinganya bergerak-gerak saat mereka mengunyah." +
                    "\n\nPanda Raksasa juga masih bersaudara dengan Panda Merah, tetapi mereka dinamai mirip sepertinya karena kebiasaan mereka memakan bambu. Sebelum hubungannya dengan Panda Merah ditemukan pada tahun 1901, Panda Raksasa dikenal sebagai beruang berwarna dua." +
                    "\n\nSelama puluhan tahun, klasifikasi taksonomi panda yang tepat diperdebatkan karena baik Panda Raksasa maupun Panda Merah memiliki ciri-ciri seperti beruang dan rakun. Namun, pengujian genetika mengungkapkan bahwa Panda Raksasa adalah beruang sejati dan termasuk keluarga Ursidae. Saudara terdekatnya dalam keluarga beruang adalah Beruang Berkacamata di Amerika Selatan. Sekarang masih diperdebatkan apakah Panda Merah termasuk keluarga Ursidae atau keluarga rakun, Procyonidae."
        ),
        arrayOf(
            "Ular",
            R.drawable.ular,
            "Ular adalah kelompok reptilia tidak berkaki dan bertubuh panjang yang tersebar luas di dunia. Secara ilmiah, semua jenis ular dikelompokkan dalam satu subordo, yaitu Serpentes dan juga merupakan anggota dari ordo Squamata, bersama-sama dengan kadal." +
                    "\n\nUlar diperkirakan telah berevolusi dari kadal tanah sejak pertengahan zaman Jurassic (174,1-163,5 juta tahun yang lalu). Fosil ular tertua yang diketahui, Eophis underwoodi, adalah ular kecil yang hidup di daratan Inggris selatan sekitar 167 juta tahun yang lalu." +
                    "\n\nCiri-ciri utama ular adalah bertubuh panjang dan tidak memiliki kaki. Akan tetapi, ciri-ciri tersebut juga dimiliki oleh beberapa jenis kadal (misalnya kadal-pensil Burton). Ciri-ciri selanjutnya adalah, ular tidak memiliki indera pendengaran samasekali. Akan tetapi, ular bisa merasakan getaran melalui rahang bawahnya saat menempel di tanah atau di permukaan. Ular tidak memiliki kelopak mata yang dapat di buka-tutup, dan matanya selalu terbuka selama hidupnya. Walaupun begitu, mata ular dilapisi oleh sisik bening yang melindunginya dari kotoran. Ciri utama lainnya adalah, lidah ular bercabang dua dengan masing-masing cabangnya berukuran panjang dan runcing, dan dapat dijulurkan ke luar melalui rongga di tengah bibirnya. Dengan kata lain, ular dapat menjulurkan lidahnya dalam keadaan mulut tertutup rapat. Ular menjulurkan lidahnya untuk mendeteksi bau di udara, sementara hidung ular hanya digunakan untuk bernafas. Setiap cabang lidah ular dilengkapi dengan kelenjar yang dapat menangkap partikel bau di udara, lalu ular akan menarik lidahnya kembali ke mulut. Selanjutnya, partikel-partikel bau yang menempel di lidahnya itu disalurkan ke sebuah organ pengenal bau yang terletak di langit-langit rahang atasnya. Organ tersebut disebut Organ Jacobson. Setelah diidentifikasi, organ tersebut mengirimkan informasi ke otak ular. Otak akan memprosesnya dan menentukan hal selanjutnya yang akan dilakukan oleh ular, berdasarkan hasil identifikasi bau tersebut, misalnya memburu sumber bau yang berupa mangsanya. Beberapa jenis ular memiliki organ khusus untuk mengidentifikasi temperatur lingkungannya. Alat ini disebut Termoreseptor, dan berguna bagi ular untuk mengetahui dan melacak keberadaan hewan berdarah panas seperti burung dan mamalia. Organ ini dapat berupa sepasang lubang yang terletak di antara mata dan lubang hidung (misalnya pada ular-ular Crotalidae), atau berupa lapisan yang terletak di sela-sela sisik bibir atas (misalnya pada jenis-jenis Boidae dan Pythonidae)." +
                    "\n\nUlar merupakan salah satu reptilia yang paling sukses berkembang di dunia. Mereka dapat ditemukan di semua tipe habitat: hutan, padang rumput, gurun/padang pasir, sungai, danau, dataran tinggi, perkebunan, persawahan, laut, dan juga di pemukiman manusia. Akan tetapi, seperti halnya reptilia lainnya, ular tidak terdapat dan tidak bisa ditemukan di daerah dingin seperti di puncak gunung dan di daerah lingkar kutub (beberapa spesies ada yang mampu hidup di daerah dekat kutub utara). Ular juga tidak terdapat dan tidak ditemukan di Irlandia, Selandia baru, Greenland, pulau-pulau terisolasi di Pasifik seperti Hawaii, serta di Samudera Atlantik." +
                    "\n\nSebagian besar ular hidup dan tinggal di tanah, sebagian lagi hidup dan tinggal di atas pohon atau tanaman. Walau begitu,sebagian besar spesies ular di tanah dapat memanjat pohon. Selain di tanah dan pohon, ular juga hidup di perairan, bahkan ada golongan ular yang hidup di air dan tidak pernah berkelana di darat samasekali, misalnya ular-ular golongan Hydrophiidae." +
                    "\n\nUlar adalah hewan karnivora, mereka memangsa berbagai jenis hewan lebih kecil dari tubuhnya. Ular pohon dan ular darat memangsa burung, mamalia, kodok, jenis-jenis reptil yang lain, termasuk telur-telurnya. Ular-ular besar seperti ular sanca kembang dapat memangsa kambing, kijang, rusa dan bahkan manusia. Ular-ular yang hidup di perairan memangsa ikan, kodok, berudu, dan bahkan telur ikan." +
                    "\n\nUlar memakan seluruh mangsanya tanpa sisa dan mampu mengkonsumsi mangsa tiga kali lebih besar dari diameter kepala mereka. Hal ini dikarenakan rahang mereka lebih rendah dan dapat terpisah dari rahang atas. Selain itu ular memiliki gigi menghadap kebelakang yang menahan mangsanya tetap di mulut mereka. Hal ini mencegah mangsa melarikan diri." +
                    "\n\nUlar memakan mangsanya bulat-bulat, tanpa dikunyah menjadi keping-keping yang lebih kecil. Gigi di mulut ular tidak memiliki fungsi untuk mengunyah, melainkan sekadar untuk memegang mangsanya agar tidak mudah terlepas. Agar lancar menelan, ular biasanya memilih menelan mangsa dengan kepalanya lebih dahulu." +
                    "\n\nBeberapa jenis ular, seperti sanca dan ular tikus, membunuh mangsa dengan cara melilitnya hingga tak bisa bernapas. Ular-ular berbisa membunuh mangsa dengan bisanya, yang dapat melumpuhkan sistem saraf pernapasan dan jantung (neurotoksin), atau yang dapat merusak peredaran darah (hemotoksin), dalam beberapa menit saja. Bisa yang disuntikkan melalui gigitan ular itu biasanya sekaligus mengandung enzim pencerna, yang memudahkan pencernaan makanan itu apabila telah ditelan."
        ),
    )

    val listData: ArrayList<Hewan>
        get() {
            val list = ArrayList<Hewan>()
            for (Data in data) {
                val hewan = Hewan()
                hewan.nama = Data[0] as String
                hewan.foto = Data[1] as Int
                hewan.detail = Data[2] as String

                list.add(hewan)
            }
            return list
        }
}